version: '3.8'
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'

  client-backend:
    image: client:0.0.1
    build:
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db